### ISSUE TITLE
dependencies reference nonexistent parent node ('botdevtestbot'

### ISSUE THREAD

**Issue by alibaltschun** [Ali-Toosi/django-tgbot#7]
error after create bot app

m1, python3, 

```
(venv_attendance) (base) baltschun@baltschuns-MacBook-Air app % python manage.py migrate
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/db/migrations/loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration ananas_attendance_onlybot.0002_auto_20201109_1648 dependencies reference nonexistent parent node ('botdevtestbot', '0001_initial')

```

**Comment by Ali-Toosi** [comment]
Thanks for raising this. It is now resolved and you can upgrade with pip to have the issue fixed. Please close this thread once you have checked and it's working on your side too.
